import { Header } from "@/components/header/Header";
import "./globals.css";
import "./reset.css";
import type { Metadata } from "next";
import { Footer } from "@/components/footer/Footer";

export const metadata: Metadata = {
  title: "ЮНИТ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="background-image">
          <Header />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
