import "./globals.css";
import type { Metadata } from "next";
import { Footer } from "@/app/components/Footer";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "ЮНИТ",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin", "cyrillic"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.className}`}>
      <body>
        <div>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
